"""
agents/extractor_agent.py — Structured data extraction agent.

Responsibilities:
  1. For each ScrapedDocument, build a precision-crafted extraction prompt.
  2. Send text to the LLM and parse the JSON response.
  3. Score per-field confidence so the Critic knows what to verify.
  4. Handle chunked extraction (large documents) and merge results.
  5. Write ExtractedRow objects into state.rows.

Prompt engineering philosophy (this is the most critical part of the system):
  • System prompt tells the LLM its exact role and output format.
  • Field definitions are generated by the LLM itself (not hardcoded) based on
    the column names AND the topic — this ensures definitions are domain-appropriate.
  • A realistic example row is generated by the LLM and injected as a few-shot
    hint — this dramatically reduces hallucinations.
  • Explicit rules prevent common failure modes: don't invent data, don't merge
    rows, output N/A not null/empty, one object per distinct item.
  • For multi-entity documents (lists of drugs, papers, companies) the LLM
    returns multiple JSON objects.
  • For single-entity documents (one paper, one company page) it returns one.
"""

from __future__ import annotations

import json
import re
import time
from typing import Any

from rich.console import Console

import config as cfg
from agents.scraper_agent import ScrapedDocument
from state import ColumnDef, ExtractedRow, SessionState
from tools.llm_tools import LLMClient
from tools.pdf_tools import chunk_text, select_best_chunks

console = Console()

# Phrases the LLM uses for missing values — these all map to N/A
_EMPTY_VALS = frozenset({
    "n/a", "none", "not specified", "not mentioned", "not provided",
    "not explicitly mentioned", "unspecified", "unknown", "na", "nil", "",
    "not available", "not found", "not discussed", "not applicable",
    "not stated", "not reported", "not described", "null", "—", "-",
})

# Max chunks to send in a single Ollama-style chunked extraction
_MAX_CHUNKS_PER_CALL = 6


def _is_empty(v: str) -> bool:
    return str(v).strip().lower() in _EMPTY_VALS


# ═══════════════════════════════════════════════════════════════════════════════
# Prompt builders
# ═══════════════════════════════════════════════════════════════════════════════

def _build_system_prompt(
    columns: list[ColumnDef],
    topic: str,
    example_json: str,
    is_table: bool = False,
) -> str:
    """
    Build the system prompt for extraction.

    This is the most carefully crafted prompt in the system.
    It tells the LLM exactly what to do, what not to do, and gives
    a concrete example of the expected output format.

    Args:
        columns      — the ColumnDef objects with name, description, example
        topic        — the research topic (for context)
        example_json — a JSON string showing one realistic example row
        is_table     — True when the input is already a structured table

    Returns:
        A complete system prompt string.
    """
    # Build the field block — this is the heart of the prompt
    field_lines = []
    for col in columns:
        line = f'  "{col.name}": {col.description}'
        if col.example:
            line += f' Example: {col.example}.'
        field_lines.append(line)
    field_block = "\n".join(field_lines)

    entity_instruction = (
        "This is a STRUCTURED TABLE — return exactly ONE JSON object per data row "
        "(excluding header rows)."
        if is_table
        else (
            "Identify every DISTINCT ENTITY relevant to the topic in this text. "
            "If multiple entities exist (multiple drugs, papers, companies, etc.), "
            "return ONE JSON object per entity. "
            "If the text focuses on a single entity, return exactly one object."
        )
    )

    return f"""\
You are an expert data extraction agent specialising in {topic}.

YOUR TASK:
Extract structured information from the provided text and return it as a JSON array.

FIELD DEFINITIONS (extract EXACTLY these fields, using these precise definitions):
{field_block}

OUTPUT FORMAT:
- Return a JSON ARRAY of objects, one per distinct entity found.
- Every object must have ALL of the following keys: {', '.join(f'"{c.name}"' for c in columns)}
- Use the string "N/A" (not null, not empty, not 0) for any field where the information
  is genuinely absent from the text. Do NOT guess or invent values.
- Use exact values as written in the source text — do not paraphrase or summarize field values.
- For numeric fields, include units when present (e.g. "342 mg/kg", not just "342").
- For date fields, use the format found in the text (e.g. "March 2023", "2023-03-15").

CRITICAL RULES:
1. NEVER invent or hallucinate data. If you are not certain, use "N/A".
2. NEVER merge two distinct entities into one object.
3. NEVER omit a field — every object must have every key, even if the value is "N/A".
4. NEVER return prose, explanation, or markdown. ONLY return the JSON array.
5. {entity_instruction}
6. For confidence: if a value is explicitly stated in the text, you are confident.
   If you inferred or approximated it, use "N/A" — the Refiner will find it.

EXAMPLE OUTPUT (for reference — use actual values from the text, not these examples):
{example_json}

Now extract from the provided text. Start your response with [ immediately."""


def _build_user_message(doc: ScrapedDocument) -> str:
    """
    Build the user message containing the text to extract from.
    Prepends source context to help the LLM understand provenance.
    """
    source_line = (
        f"[SOURCE: {doc.source_url[:120]}]\n\n"
        if doc.source_url else ""
    )
    return source_line + doc.full_context()


# ═══════════════════════════════════════════════════════════════════════════════
# Column definition generation
# ═══════════════════════════════════════════════════════════════════════════════

_FIELD_DEF_SYSTEM = """\
You are a data extraction expert and domain specialist.

Given a research topic and a list of column names that a user wants to extract,
write precise, actionable field definitions that tell an LLM extraction agent
EXACTLY what value to extract for each field.

Requirements for each definition:
- Be specific to the topic (not generic).
- State the expected format (e.g., "4-digit year", "drug name in generic form",
  "numeric value with units").
- Include what to do when the field doesn't apply (usually: "use N/A").
- Be 1-2 sentences maximum — concise but complete.
- Include a concrete example value in parentheses after the definition.

Return ONLY a JSON object: {"column_name_lowercase": "definition string", ...}
Include every column. No explanation."""

_FIELD_EXAMPLE_SYSTEM = """\
You are a data extraction expert.

Given a topic and column names, generate ONE realistic example row that shows
what a correctly extracted data point looks like.

Requirements:
- Use plausible, real-looking values — not placeholders like "value here".
- Values should reflect the topic domain accurately.
- Show the format expected (units, date format, etc.).

Return ONLY a JSON array containing exactly one object.
Example format: [{"Column1": "realistic value", "Column2": "another value", ...}]"""


# ═══════════════════════════════════════════════════════════════════════════════
# Merge logic
# ═══════════════════════════════════════════════════════════════════════════════

def _merge_rows(
    all_rows: list[dict],
    columns: list[ColumnDef],
) -> list[dict]:
    """
    Deduplicate rows from chunked extraction.

    Two rows are considered duplicates if their identity fields (name, title,
    ID, etc.) match after normalisation. When duplicates exist, the row with
    more filled fields "wins" — but we prefer values from the first occurrence
    for identity fields and values from any occurrence for content fields.

    This handles the common case where the same entity is mentioned in
    multiple chunks of a large document.
    """
    if not all_rows:
        return []

    # Identify "identity" columns (name/title/id/doi) vs "content" columns
    identity_keys = {
        c.name for c in columns
        if any(kw in c.name.lower() for kw in
               ["name", "title", "id", "doi", "identifier", "drug", "compound", "gene"])
    }

    def _sig(row: dict) -> str:
        """Signature for dedup — normalised identity fields only."""
        parts = []
        for k in sorted(identity_keys):
            v = str(row.get(k, "N/A")).strip().lower()
            if v not in _EMPTY_VALS:
                parts.append(f"{k}={v[:40]}")
        return "|".join(parts) if parts else ""

    seen:   dict[str, dict] = {}
    unique: list[dict]      = []

    for row in all_rows:
        sig = _sig(row)

        if not sig:
            # No identity fields filled — keep all such rows
            unique.append(row)
            continue

        if sig in seen:
            # Merge: fill empty fields in the existing row from this row
            existing = seen[sig]
            for k, v in row.items():
                if _is_empty(str(existing.get(k, "N/A"))) and not _is_empty(str(v)):
                    existing[k] = v
        else:
            seen[sig] = row
            unique.append(row)

    return unique


# ═══════════════════════════════════════════════════════════════════════════════
# Extractor agent
# ═══════════════════════════════════════════════════════════════════════════════

class ExtractorAgent:
    """
    Extracts structured rows from ScrapedDocuments and adds them to state.

    Strategy by document size:
      ≤ MAX_TEXT_CHARS → single LLM call with full context.
      > MAX_TEXT_CHARS → chunk text, select best chunks, one LLM call per chunk,
                         merge results.

    Column definitions are generated by the LLM once per (topic, columns) pair
    and cached so subsequent documents don't pay the API cost.
    """

    def __init__(self, llm: LLMClient) -> None:
        self.llm = llm
        # Cache: (topic_hash, col_hash) → field_defs dict
        self._def_cache:     dict[str, dict[str, str]] = {}
        self._example_cache: dict[str, str]            = {}

    # ── Public API ─────────────────────────────────────────────────────────

    def run(self, docs: list[ScrapedDocument], state: SessionState) -> None:
        """
        Extract rows from all docs and add them to state.rows.

        Args:
            docs  — ScrapedDocuments from the Scraper agent
            state — the shared session state (rows will be appended here)
        """
        console.print(f"\n[bold cyan]🧠 Extractor Agent[/bold cyan]"
                      f" — {len(docs)} document(s) to process")

        # Ensure column definitions are rich and precise
        self._ensure_column_definitions(state)

        total_new = 0
        for i, doc in enumerate(docs):
            console.print(f"\n  [dim]Document {i+1}/{len(docs)}: {doc.source_url[:70]}[/dim]")

            rows = self._extract_document(doc, state)

            for row_data in rows:
                er = ExtractedRow(
                    data       = row_data,
                    source_url = doc.source_url,
                    confidence = self._score_confidence(row_data, state.columns),
                )
                state.add_row(er)
                total_new += 1

            console.print(f"  [green]✓ Extracted {len(rows)} row(s)[/green]")

            # Partial save after every document
            state.save()

        console.print(f"\n[green]✓ Extractor done — {total_new} new row(s) added[/green]")

    # ── Column definition enrichment ────────────────────────────────────────

    def _ensure_column_definitions(self, state: SessionState) -> None:
        """
        If any column is missing a description, ask the LLM to generate one.

        This is called once per run.  The cache prevents repeated API calls
        for the same (topic, columns) combination.
        """
        # Check if definitions are already in place
        needs_defs = [c for c in state.columns if not c.description.strip()]
        if not needs_defs:
            return

        cache_key = (
            state.topic[:60]
            + "|"
            + "|".join(c.name for c in state.columns[:15])
        )
        if cache_key in self._def_cache:
            defs = self._def_cache[cache_key]
        else:
            console.print("[dim]Generating field definitions via LLM…[/dim]")
            defs = self._generate_field_definitions(state.topic, state.columns)
            self._def_cache[cache_key] = defs

        # Apply definitions to column objects
        for col in state.columns:
            if not col.description.strip():
                # Try exact match first, then substring match
                defn = defs.get(col.name.lower())
                if not defn:
                    for k, v in defs.items():
                        if k in col.name.lower() or col.name.lower() in k:
                            defn = v
                            break
                if defn:
                    col.description = defn

        # Fill anything still missing with a dynamic fallback
        for col in state.columns:
            if not col.description.strip():
                col.description = self._fallback_definition(col.name, state.topic)

        # Generate example row (cached)
        example_key = cache_key + "_example"
        if example_key not in self._example_cache:
            self._example_cache[example_key] = self._generate_example(
                state.columns, state.topic
            )

    def _generate_field_definitions(
        self,
        topic: str,
        columns: list[ColumnDef],
    ) -> dict[str, str]:
        """Ask the LLM for per-field definitions specific to the topic."""
        col_list = ", ".join(f'"{c.name}"' for c in columns[:15])
        try:
            raw = self.llm.complete_json(
                system=_FIELD_DEF_SYSTEM,
                user=(
                    f'Topic: "{topic}"\n'
                    f'Columns: [{col_list}]\n\n'
                    f'Generate precise field definitions as a JSON object:'
                ),
                model=cfg.FAST_MODEL,
                max_tokens=1500,
            )
            if isinstance(raw, dict):
                return {str(k).lower(): str(v) for k, v in raw.items()}
        except Exception as exc:
            console.print(f"  [yellow]⚠ Field definition generation failed: {exc}[/yellow]")
        return {}

    def _generate_example(
        self,
        columns: list[ColumnDef],
        topic: str,
    ) -> str:
        """Ask the LLM for a realistic example extraction row."""
        col_list = ", ".join(f'"{c.name}"' for c in columns[:12])
        try:
            raw = self.llm.complete_json(
                system=_FIELD_EXAMPLE_SYSTEM,
                user=(
                    f'Topic: "{topic}"\n'
                    f'Columns: [{col_list}]\n\n'
                    f'Generate one realistic example row:'
                ),
                model=cfg.FAST_MODEL,
                max_tokens=600,
            )
            if isinstance(raw, list) and raw:
                return json.dumps(raw[:1], indent=2)
        except Exception:
            pass

        # Static fallback example
        return json.dumps(
            [{c.name: c.example or "actual extracted value" for c in columns}],
            indent=2
        )

    @staticmethod
    def _fallback_definition(col_name: str, topic: str) -> str:
        """Generate a reasonable definition from the column name alone."""
        key = col_name.strip().lower()
        patterns = [
            (r'\byear\b|\bdate\b',                    f"4-digit year or date relevant to {topic}."),
            (r'\bname\b|\btitle\b',                   f"Full name or title of the {topic} item."),
            (r'\bauthor\b|\bresearcher\b',             "Author or researcher names, comma-separated."),
            (r'\bdoi\b|\bidentifier\b|\baccession\b', "Unique identifier or DOI (e.g. 10.xxxx/xxxxx)."),
            (r'\babstract\b|\bsummary\b|\bdescription\b', "1-2 sentence summary."),
            (r'\bjournal\b|\bpublication\b|\bsource\b', "Journal or publication name."),
            (r'\bmethod\b|\btechnique\b|\bprotocol\b', f"Method or technique used in the {topic} study."),
            (r'\bresult\b|\bfinding\b|\boutcome\b',    f"Key result or finding for {topic}."),
            (r'\bspecies\b|\borganism\b',              "Biological species name (e.g. Homo sapiens)."),
            (r'\bdose\b|\bconcentration\b|\bquantity\b', "Numeric dose or concentration with units."),
            (r'\bgene\b|\bprotein\b|\bbiomarker\b',   "Gene symbol or protein name (e.g. BRCA1, p53)."),
            (r'\bdisease\b|\bcondition\b|\bindication\b', "Disease or medical condition name."),
            (r'\bstatistic\b|\bp.?value\b|\bsignificance\b', "Statistical value (e.g. p<0.05, OR=2.3)."),
            (r'\bcountry\b|\blocation\b|\bregion\b',  "Geographic location or country name."),
            (r'\bsample\b|\bparticipant\b|\bsubject\b|\bpatient\b',
             "Number of samples/participants (e.g. n=342)."),
            (r'\bprice\b|\bcost\b|\brevenue\b',       "Monetary value with currency (e.g. $42.5M)."),
        ]
        import re
        for pattern, definition in patterns:
            if re.search(pattern, key):
                return definition
        return (
            f'Extract the value for "{col_name}" from the text about {topic}. '
            "Use the exact value as written; do not paraphrase. "
            "Use N/A if not found."
        )

    # ── Document extraction ────────────────────────────────────────────────

    def _extract_document(
        self,
        doc: ScrapedDocument,
        state: SessionState,
    ) -> list[dict]:
        """
        Extract rows from a single document.

        Routing:
          - Short documents → single LLM call.
          - Long documents → chunk, select best chunks, one call per chunk, merge.
        """
        col_names  = [c.name for c in state.columns]
        example_key = (
            state.topic[:60]
            + "|"
            + "|".join(c.name for c in state.columns[:15])
            + "_example"
        )
        example_json = self._example_cache.get(example_key, "[]")

        context = doc.full_context()

        # Single-pass extraction for short documents
        if len(context) <= cfg.MAX_TEXT_CHARS:
            return self._extract_single(doc, state, example_json)

        # Chunked extraction for long documents
        console.print(f"  [dim]Long document ({len(context):,} chars) — chunking…[/dim]")
        return self._extract_chunked(doc, state, example_json)

    def _extract_single(
        self,
        doc: ScrapedDocument,
        state: SessionState,
        example_json: str,
    ) -> list[dict]:
        """Single LLM call for short/medium documents."""
        system = _build_system_prompt(
            columns      = state.columns,
            topic        = state.topic,
            example_json = example_json,
            is_table     = bool(doc.tables),
        )
        user = _build_user_message(doc)

        try:
            raw = self.llm.complete(
                system     = system,
                user       = user,
                max_tokens = cfg.MAX_TOKENS_EXTRACTION,
            )
            rows = self._parse_extraction(raw, state.columns)
            return rows
        except Exception as exc:
            console.print(f"  [red]✗ Extraction failed: {exc}[/red]")
            return []

    def _extract_chunked(
        self,
        doc: ScrapedDocument,
        state: SessionState,
        example_json: str,
    ) -> list[dict]:
        """
        Chunk the document, select the most relevant chunks, extract from each.

        Strategy:
          1. Chunk text at section boundaries.
          2. Score chunks with embeddings + structural heuristics.
          3. Select top _MAX_CHUNKS_PER_CALL chunks.
          4. Extract from each chunk independently.
          5. Merge results (deduplicate entities that span multiple chunks).
        """
        col_names = [c.name for c in state.columns]
        chunks    = chunk_text(doc.text)
        best      = select_best_chunks(
            chunks,
            col_names,
            max_chunks = _MAX_CHUNKS_PER_CALL,
            llm_client = self.llm,
        )
        console.print(f"  [dim]Using {len(best)}/{len(chunks)} chunks[/dim]")

        all_rows: list[dict] = []
        system = _build_system_prompt(
            columns      = state.columns,
            topic        = state.topic,
            example_json = example_json,
            is_table     = False,
        )

        for ci, chunk in enumerate(best):
            chunk_doc = ScrapedDocument(
                text       = chunk,
                source_url = doc.source_url,
                method     = doc.method,
            )
            try:
                raw = self.llm.complete(
                    system     = system,
                    user       = _build_user_message(chunk_doc),
                    max_tokens = cfg.MAX_TOKENS_EXTRACTION,
                )
                rows = self._parse_extraction(raw, state.columns)
                all_rows.extend(rows)
                console.print(f"  [dim]Chunk {ci+1}: {len(rows)} row(s)[/dim]")
            except Exception as exc:
                console.print(f"  [dim red]Chunk {ci+1} failed: {exc}[/dim red]")

        # Merge duplicates from different chunks
        merged = _merge_rows(all_rows, state.columns)
        console.print(f"  [dim]After merge: {len(merged)} unique row(s)[/dim]")
        return merged

    # ── Response parsing ────────────────────────────────────────────────────

    def _parse_extraction(
        self,
        raw: str,
        columns: list[ColumnDef],
    ) -> list[dict]:
        """
        Parse the LLM's JSON response into a list of row dicts.

        Applies:
          - Markdown fence stripping
          - Unquoted N/A fix
          - Fuzzy key matching (LLM sometimes changes capitalisation)
          - Empty-row filtering
        """
        if not raw:
            return []

        try:
            # Strip markdown and fix common issues
            cleaned = re.sub(r"```(?:json)?\s*", "", raw).strip().rstrip("`")
            cleaned = re.sub(r":\s*N/A\s*([,\}\]])", r': "N/A"\1', cleaned)

            # Find the outermost JSON array or object
            for opener, closer in [("[", "]"), ("{", "}")]:
                si = cleaned.find(opener)
                if si == -1:
                    continue
                ei = cleaned.rfind(closer)
                if ei > si:
                    parsed = json.loads(cleaned[si:ei+1])
                    if isinstance(parsed, dict):
                        parsed = [parsed]
                    if isinstance(parsed, list):
                        return self._normalise_rows(parsed, columns)

            # Try appending a bracket in case response was truncated
            for opener, closer in [("[", "]"), ("{", "}")]:
                si = cleaned.find(opener)
                if si != -1:
                    try:
                        parsed = json.loads(cleaned[si:] + closer)
                        if isinstance(parsed, dict):
                            parsed = [parsed]
                        if isinstance(parsed, list):
                            return self._normalise_rows(parsed, columns)
                    except json.JSONDecodeError:
                        pass

        except json.JSONDecodeError as exc:
            if cfg.DEBUG:
                console.print(f"  [dim red]JSON parse error: {exc}\nRaw: {raw[:400]}[/dim red]")

        return []

    def _normalise_rows(
        self,
        rows: list[Any],
        columns: list[ColumnDef],
    ) -> list[dict]:
        """
        Normalise parsed rows:
          - Skip non-dict items
          - Map LLM keys to canonical column names (case-insensitive fuzzy match)
          - Fill missing columns with "N/A"
          - Filter rows where everything is N/A
        """
        result = []
        col_map = {c.name.lower(): c.name for c in columns}

        for raw_row in rows:
            if not isinstance(raw_row, dict):
                continue

            # Normalise keys
            norm: dict[str, str] = {}
            for k, v in raw_row.items():
                canonical = self._resolve_column(str(k), col_map)
                if canonical:
                    norm[canonical] = str(v).strip() if v is not None else "N/A"

            # Fill all expected columns
            row: dict[str, str] = {}
            for col in columns:
                row[col.name] = norm.get(col.name, "N/A")

            # Skip rows where every field is empty
            has_data = any(not _is_empty(v) for v in row.values())
            if has_data:
                result.append(row)

        return result

    @staticmethod
    def _resolve_column(
        llm_key: str,
        col_map: dict[str, str],
    ) -> str | None:
        """
        Map an LLM-returned key to a canonical column name.

        Tries:
          1. Exact lowercase match
          2. Substring match (LLM may abbreviate)
          3. Reverse substring match
        """
        key = llm_key.lower().strip()
        # Exact
        if key in col_map:
            return col_map[key]
        # Substring
        for canonical_lower, canonical in col_map.items():
            if key in canonical_lower or canonical_lower in key:
                return canonical
        return None

    # ── Confidence scoring ─────────────────────────────────────────────────

    @staticmethod
    def _score_confidence(
        row_data: dict[str, str],
        columns: list[ColumnDef],
    ) -> dict[str, float]:
        """
        Assign a confidence score per field.

        Simple heuristic:
          1.0 — value is present and non-empty (LLM found something)
          0.0 — value is N/A or empty (LLM didn't find it)

        The Critic agent uses these scores to decide which fields to retry.
        In a future version, we could ask the LLM to output confidence
        alongside each value, but this adds latency and cost.
        """
        scores: dict[str, float] = {}
        for col in columns:
            val = str(row_data.get(col.name, "N/A")).strip()
            scores[col.name] = 0.0 if _is_empty(val) else 1.0
        return scores